MyFeed/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'',include(('MyFeedapp.urls','MyFeedapp'),namespace='feed')),
]

MyFeedapp/urls.py
from django.contrib import admin
from django.urls import path
from MyFeedapp.views.webPages import *
from MyFeedapp.views.search_view import *
from MyFeedapp.views.save_view import *
from MyFeedapp.views.authentication_view import *
from MyFeedapp.views.user_web_page import *

urlpatterns = [
    path(r'',HomePage.as_view(),name='first_page'),
    path(r'home/',HomePage.as_view(),name='home_page'),
    path(r'sports/',SportsPage.as_view(),name='sports_page'),
    path(r'entertainment/',EntertainmentPage.as_view(),name='entertainment_page'),
    path(r'helth/', HomePage.as_view(), name='helth_page'),
    path(r'international/', InternationalPage.as_view(), name='international_page'),
    path(r'tech/', TechnologyPage.as_view(), name='tech_page'),
    path(r'science/', SciencePage.as_view(), name='science_page'),
    path(r'business/', BusinessPage.as_view(), name='business_page'),
    path(r'query/',search, name='search_page'),
    path(r'save/',save,name="save_page"),
    path(r'remove/',remove,name="remove_page"),
    path(r'signup/',signUp.as_view(),name="signup_page"),
    path(r'login/',loginUser.as_view(),name='login_page'),
    path(r'logout/',logout_view,name='logout_page'),
    path(r'saved/',SavedArticles.as_view(),name='user_saved_page'),
]

MyFeedapp/models.py
from django.core.validators import validate_comma_separated_integer_list
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Article(models.Model):
    author = models.CharField(max_length=50,null=True)
    title = models.CharField(max_length=120)
    description = models.CharField(max_length=700,null=True)
    url = models.URLField()
    urlToImage = models.URLField(null=True)
    publishedAt = models.CharField(max_length=20,null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Source(models.Model):

    id = models.CharField(max_length=40,primary_key=True)
    name = models.CharField(max_length=50)
    article = models.OneToOneField(Article,on_delete=models.DO_NOTHING)

MyFeedapp/forms/signupForm.py
from django import forms

class signUpForm(forms.Form):
    first_name = forms.CharField(
        required=True,
        widget=forms.TextInput,
    )
    last_name= forms.CharField(
        required=True,
        widget=forms.TextInput,
    )
    username = forms.CharField(
        required=True,
        widget=forms.EmailInput,
    )
    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput
    )

class loginForm(forms.Form):
    username = forms.CharField(
        required=True,
        widget=forms.TextInput,
    )
    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput
    )

MyFeedapp/views/authentication_view.py
from django import forms
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from MyFeedapp.forms.signupForm import *
from MyFeedapp.models import *
from django.contrib.auth import logout,login

def logout_view(request):
    logout(request)

    return redirect(reverse_lazy('feed:home_page'))

class loginUser(View):
    def get(self,request):
        form = loginForm

        return render(
            request,
            template_name='signUpAndLogin.html',
            context={'form':form,'Title':"Login","link_to_next":"feed:signup_page","text_of_next":"Sign Up",'submit_text':"Log In"}
        )

    def post(self,request):
        form = loginForm(request.POST)

        if form.is_valid() :
            user = authenticate(
                username=form.cleaned_data['username'],
                password = form.cleaned_data['password']
            )
            if user is not None:
                login(request,user)
                return redirect(reverse_lazy("feed:home_page"))
        else:
            return redirect(reverse_lazy('feed:login_page'))

class signUp(View):

    def get(self,request):

        form = signUpForm
        return render(
            request,
            template_name='signUpAndLogin.html',
            context={'form':form,'Title':"Sign Up","link_to_next":"feed:login_page","text_of_next":"Login",'submit_text':"Lets Start"}
        )

    def post(self,request):
        form = signUpForm(request.POST)

        if form.is_valid():
            try:
                user = authenticate(
                    username=form.cleaned_data['username'],
                    password=form.cleaned_data['password']
                )
                if user is None:
                    user = User.objects.create_user(
                        **form.cleaned_data
                    )
                    user.save()
                    login(request, user)
                    return redirect(reverse_lazy("feed:home_page"))
                return redirect(reverse_lazy("feed:signup_page"))
            except:
                return redirect(reverse_lazy("feed:signup_page"))
        # return render(
        #         request,
        #         template_name='collageBootstrap.html',
        #         context={'Headers':["ID","Name", "Acronym", "Email"],'Title': "Collage Details",'Values':Collage.objects.all()}
        #     )

MyFeedapp/views/jsonRequest_view.py
from urllib import request
from datetime import datetime
import json


def getData(url):
    """returns the top 20 json objects of the specified url :)"""
    import ssl
    ssl._create_default_https_context = ssl._create_unverified_context
    url = url.replace(' ','%20')
    response = request.urlopen(url)
    string = response.read().decode('utf-8')
    json_Response = json.loads(string)
    if json_Response['status'] != 'ok':
        print('error occured :status '+json_Response['status'])
        return None
    return json_Response['articles']

def converJsonDateToPython(Articles):
    """Converts the json date string in each article to the python date"""
    i = 0
    for article in Articles:
        article['publishedAt']=article['publishedAt'].replace('+','Z')
        article['publishedAt']=article['publishedAt'].split('Z')[0]
        article['publishedAt'] = article['publishedAt'].split('.')[0]
        pydate = datetime.strptime(article['publishedAt'],"%Y-%m-%dT%H:%M:%S")
        article['publishedAt']=pydate.strftime("%d/%m/%Y, %H:%M")
        article['id'] = i
        i += 1
    return Articles

MyFeedapp/views/save_view.py
# from django.contrib.auth.mixins import LoginRequiredMixin
# from django.views.generic import CreateView
#
# from MyFeedapp.models import *
#
# class addStudentView(LoginRequiredMixin,CreateView):
#     login_url = '/login/'
#     form_class = addStudent
#     template_name = 'addStudentTemplate.html'
#     model =
#     def post(self, request, *args, **kwargs):
#         import ipdb
#         ipdb.set_trace()
#         collage = Collage.objects.get(id=int(self.kwargs['id']))
#         student_form = addStudent(request.POST)
#         mock_test_form=addMockTest(request.POST)
#
#         if student_form.is_valid():
#             stu = student_form.save(commit=False)
#             stu.college=collage
#             stu.save()
#
#             if mock_test_form.is_valid():
#                 mckTest = mock_test_form.save(commit=False)
#                 mckTest.calulateTotal()
#                 mckTest.student=stu
#                 mckTest.save()
#         return HttpResponse(reverse_lazy('onlineapp:collages_html'))
#
#
#
from django.http import JsonResponse
import json
import ast
from MyFeedapp.models import *


def save(request):

    ab=list()
    try:
        for i in request.GET.keys():
            ab.append(i)
        article = ast.literal_eval("".join(ab))
        source = article.pop('source')
        id = article.pop('id')
        articleObj = Article(**article)
        articleObj.user = request.user
        articleObj.save()
        data = {'is_saved': True, }
    except Exception as ex:
        data = {'is_saved': False, }
    return JsonResponse(data)


def remove(request):
    ab=list()
    for i in request.GET.keys():
        ab.append(i)
    articleId = int(ab[0])
    try:
        articleObj = Article.objects.get(id=articleId)
        articleObj.delete()
        data = {'is_removed': True, }
    except Exception as ex:
        data = {'is_removed': False, }
    return JsonResponse(data)

MyFeedapp/views/search_view.py
from django.shortcuts import render

from MyFeedapp.models import *
from django.views.generic import ListView
from MyFeedapp.views.jsonRequest_view import getData,converJsonDateToPython
from MyFeedapp.views.url_option_management import *


def search(request):
    context = {}
    context['Title'] = ""
    context['Articles'] = None
    if request.method == "POST":
        # Get the posted form
        query= request.POST['search']
        url = search_url(query="q="+str(query))
        jsonObjects = getData(url)
        jsonObjects = converJsonDateToPython(jsonObjects)
        context['Title'] = query
        context['Articles'] = jsonObjects
    return render(request, 'articles.html', context)

MyFeedapp/views/url_option_management.py
__Base_Url = "use your api provider url"
__Api_key = "use your api key given by the provider"
__Search_URL="search url from the api provider "


Business = "category=business"
Entertainment = "category=entertainment"
General = "category=general"
Health = "category=health"
Science = "category=science"
Sports = "category=sports"
Technology = "category=technology"
Language_Eng = "language=en"

country_india = "country=in"


def get_url(**kwargs):
    "return the url with the options"
    url = __Base_Url
    for var in kwargs:
        url += kwargs[var] +'&'
    url += __Api_key
    return url

def search_url(**kwargs):
    "return the url with the options"
    url = __Search_URL
    for var in kwargs:
        url += kwargs[var] +'&'
    url += __Api_key
    return url

MyFeedapp/views/user_web_page.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from MyFeedapp.models import *
from django.views.generic import ListView
from MyFeedapp.views.jsonRequest_view import getData,converJsonDateToPython
from MyFeedapp.views.url_option_management import *

class SavedArticles(LoginRequiredMixin,ListView):
    template_name = 'user_saved_articles.html'
    login_url = '/login/'
    context_object_name = 'Values'
    queryset = Article.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = {}
        # import ipdb
        # ipdb.set_trace()
        user = self.request.user
        Articles = Article.objects.filter(user=user)
        num_of_articles = len(Articles)
        if num_of_articles == 0:
            context['is_data_available'] = False
        else:
            context['is_data_available'] = True
        context['Title'] = "Saved Articles"
        context['Articles']=Articles
        return context

MyFeedapp/views/webPages.py
from MyFeedapp.models import *
from django.views.generic import ListView
from MyFeedapp.views.jsonRequest_view import getData,converJsonDateToPython
from MyFeedapp.views.url_option_management import *


class HomePage(ListView):
    template_name = 'articles.html'
    login_url = '/login/'
    context_object_name = 'Values'
    queryset = Article.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        url = get_url(country=country_india,category = General)
        jsonObjects = getData(url)
        jsonObjects=converJsonDateToPython(jsonObjects)
        context = {}
        context['Title'] = "Home"
        context['Articles']=jsonObjects
        return context

class InternationalPage(ListView):
    template_name = 'articles.html'
    login_url = '/login/'
    context_object_name = 'Values'
    queryset = Article.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        url = get_url(language = Language_Eng)
        # import ipdb
        # ipdb.set_trace()
        jsonObjects = getData(url)
        jsonObjects = converJsonDateToPython(jsonObjects)
        context = {}
        context['Title'] = "International"
        context['Articles']=jsonObjects
        return context


class SportsPage(ListView):
    template_name = 'articles.html'
    login_url = '/login/'
    context_object_name = 'Values'
    queryset = Article.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        url = get_url(country=country_india,category = Sports)
        jsonObjects = getData(url)
        jsonObjects = converJsonDateToPython(jsonObjects)
        context = {}
        context['Title'] = "Sports"
        context['Articles']=jsonObjects
        return context


class EntertainmentPage(ListView):
    template_name = 'articles.html'
    login_url = '/login/'
    context_object_name = 'Values'
    queryset = Article.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        url = get_url(country=country_india,category = Entertainment)
        jsonObjects = getData(url)
        jsonObjects = converJsonDateToPython(jsonObjects)
        context = {}
        context['Title'] = "Movies"
        context['Articles']=jsonObjects
        return context

class TechnologyPage(ListView):
    template_name = 'articles.html'
    login_url = '/login/'
    context_object_name = 'Values'
    queryset = Article.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        url = get_url(country=country_india,category = Technology)
        jsonObjects = getData(url)
        jsonObjects = converJsonDateToPython(jsonObjects)
        context = {}
        context['Title'] = "Technology"
        context['Articles']=jsonObjects
        return context

class SciencePage(ListView):
    template_name = 'articles.html'
    login_url = '/login/'
    context_object_name = 'Values'
    queryset = Article.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        url = get_url(country=country_india,category = Science)
        jsonObjects = getData(url)
        jsonObjects = converJsonDateToPython(jsonObjects)
        context = {}
        context['Title'] = "Science"
        context['Articles']=jsonObjects
        return context

class HelthPage(ListView):
    template_name = 'articles.html'
    login_url = '/login/'
    context_object_name = 'Values'
    queryset = Article.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        url = get_url(country=country_india,category = Health)
        jsonObjects = getData(url)
        jsonObjects = converJsonDateToPython(jsonObjects)
        context = {}
        context['Title'] = "Helth"
        context['Articles']=jsonObjects
        return context

class BusinessPage(ListView):
    template_name = 'articles.html'
    login_url = '/login/'
    context_object_name = 'Values'
    queryset = Article.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        url = get_url(country=country_india,category = Business)
        jsonObjects = getData(url)
        jsonObjects = converJsonDateToPython(jsonObjects)
        context = {}
        context['Title'] = "Business"
        context['Articles']=jsonObjects
        return context

MyFeedapp/templates/articles.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html lang="en">

<head>
    <title>{{Title}}</title>
    <link rel="stylesheet" href="{% static 'article.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <style>

        #articleimage{
        height: 100% !important;
        width: 100% !important;
        }


    </style>
    <script>

    window.onload = function() {
        document.getElementById("loader").style.display="none";
        document.getElementById("menu").style.display="block";
        document.getElementById("articles").style.display="block";
        var save_buttons = document.getElementsByClassName("btn btn-primary");
        var i = 0;
        for(i = 0;i<save_buttons.length;i++)
        {
            save_buttons[i].onclick=function() {saveArticleFunction(this);}
            console.log(save_buttons[i].id);
        }
    };
        function saveArticleFunction(item)
        {
            var article =  item.id;
            alert("Button Pressed.");
            $.ajax({
                url: '/save/',
                data:article,
                dataType: 'json',
                success: function (data) {
                console.log(data);
                    if (data.is_saved) {
                        alert(" Article Saved.");
                    }
                    else{
                        alert(" Article Not Saved.");
                    }
                }
            });
        }
    </script>
</head>
<body >

    {% include 'basePageDisplay.html' %}
<div id="articles" class="container-fluid"  style="background-image:url({% static 'grey_wash_wall.png' %}); background-repeat:repeat; background-attachment: fixed;display:none;">
    <p>.</p>
    <div class="row" style="margin-top: 70px !important;font-size: initial !important;">
    {% for article in Articles %}
        {% if article.title %}
  <div class="col-sm-6 col-md-4" style="height: 600px !important;">
    <div class="thumbnail">
      <img class="lib-img-show" style="height:200px !important;" src="{{article.urlToImage}}"  alt=" img of {{article.title}}"/>
      <div class="caption" style="height:300px;" >
        <h3><a href="{{article.url}}">{{article.title}}</a></h3>
          <p>{{article.description}}</p>
          <div>
              {{article.publishedAt}}
          </div>
      {% if request.user.is_authenticated %}
        <p><button style="float: right;" id="{{article}}" type="button" class="btn btn-primary">Save</button></p>
      {% endif %}
      </div>
    </div>
  </div>

<!--</div>-->
        {% endif %}
    {% endfor %}
    </div>

</div>
</body>
</html>
<!--author = models.CharField(max_length=50)-->
    <!--title = models.CharField(max_length=120)-->
    <!--desciption = models.CharField(max_length=700)-->
    <!--source_url = models.URLField()-->
    <!--url_to_image = models.URLField()-->
    <!--publishedAt = models.DateTimeField()-->

MyFeedapp/templates/basePageDisplay.html
{% load static from staticfiles %}
<html>
<head>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="icon" href="{% static 'gloab.png' %}" type="image/gif" >
    <style>
        #articleimage{
        height: 100% !important;
        width: 100% !important;
        }
        #loader {
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid #3498db;
  width: 60px;
  height: 60px;
  margin-top: 20%;
  margin-left: 48%;

  -webkit-animation: spin 2s linear infinite; /* Safari */
  animation: spin 1s linear infinite;
}

/* Safari */
@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
    </style>

</head>
<body>
    <div id="loader"></div>
    <div id="menu" style="display:none;">
    <!--<nav  class="navbar navbar-default navbar-fixed-top" style="background:rgb(0,0,0);">-->
        <!--<div class="container-fluid" >-->
            <!--<div class="navbar-header">-->
                <!--<a class="navbar-brand" href="#">MyFeed</a>-->
            <!--</div>-->
            <!--<ul class="nav navbar-nav">-->
                <!--<li><a href="{% url 'feed:home_page' %}">Home</a></li>-->
                <!--<li><a href="{% url 'feed:sports_page' %}">Sports</a></li>-->
                <!--<li><a href="{% url 'feed:entertainment_page' %}">Entertainment</a></li>-->
                <!--<li><a href="{% url 'feed:tech_page' %}">Technology</a></li>-->
                <!--<li><a href="{% url 'feed:science_page' %}">Science</a></li>-->
                <!--<li><a href="{% url 'feed:business_page' %}">Business</a></li>-->
                <!--<li><a href="{% url 'feed:international_page' %}">Internatonal</a></li>-->
                <!--{% if request.user.is_authenticated %}-->
                <!--<li><a href="{% url 'feed:user_saved_page' %}">{{request.user.first_name}}</a></li>-->
                <!--<li><a href="{% url 'feed:logout_page' %}">Logout</a></li>-->
                <!--{% else %}-->
                    <!--<li><a href="{% url 'feed:login_page' %}">Login</a></li>-->
                <!--{% endif %}-->
            <!--</ul>-->

            <!--<form name = "form" action = "{% url 'feed:search_page' %}" method = "POST"  >-->
                        <!--{% csrf_token %}-->
                        <!--<input type="text" class = "search" name="search"  placeholder="Search..">-->
            <!--</form>-->
        <!--</div>-->
    <!--</nav>-->

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top" style="font-size: initial !important;">
  <a class="navbar-link" style="color:white;" href="#">MY FeeD </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mx-auto">
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'feed:home_page' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'feed:sports_page' %}">Sports</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'feed:entertainment_page' %}">Entertainment</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="{% url 'feed:tech_page' %}">Technology</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="{% url 'feed:science_page' %}">Science</a>
      </li>
      <li class="nav-item"><a class="nav-link" href="{% url 'feed:business_page' %}">Business</a></li>
      <li class="nav-item"><a class="nav-link" href="{% url 'feed:international_page' %}">Internatonal</a></li>
      {% if request.user.is_authenticated %}
      <li class="nav-item"><a class="nav-link" href="{% url 'feed:user_saved_page' %}">Saved Pages of {{request.user.first_name}}</a></li>
      <li class="nav-item"><a class="nav-link" href="{% url 'feed:logout_page' %}">Logout</a></li>
      {% else %}
      <li class="nav-item"><a class="nav-link" href="{% url 'feed:login_page' %}">Login</a></li>
      {% endif %}
    </ul>
    <form class="form-inline" action = "{% url 'feed:search_page' %}" method = "POST" >
        {% csrf_token %}
      <!--<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
      <input class="form-control mr-sm-2" type="text" name="search"  placeholder="Search..">
    </form>
  </div>
</nav>
</div>
</body>
</html>

MyFeedapp/templates/signUpAndLogin.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'article.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{Title}}</title>
    <style>
        #centerArrange{
        margin-left: 200px;
        margin-right: 200px
        }
        #tabl{
        margin-top: 50px;
        background: transparent;

        font-size:20px;
        }
        td {
            color:white;
        }

        input {
            width: 150px;
            box-sizing: border-box;
            border: 2px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
            color:black;
            background-color: white;
            background-position: 10px 10px;
            background-repeat: no-repeat;
            padding: 12px;
            -webkit-transition: width 0.4s ease-in-out;
            transition: width 0.4s ease-in-out;
        }
         input:focus {
            width: 300px;
            background-image:none;
            color:black;
        }
    </style>

    <script type="text/javascript">

    window.onload = function() {
        document.getElementById("loader").style.display="none";
        document.getElementById("menu").style.display="block";
        document.getElementById("login").style.display="block";
        }
    </script>
</head>
<body style="background-image:url({% static 'signup.png' %}); background-repeat:repeat; background-attachment: fixed;">
{% include 'basePageDisplay.html' %}
<div id="login" style="display:none;">
<div style="margin-left: 30%;width: 40%;margin-top:70px;">
    <div class="container-fluid"  style="font-size: initial !important;">
        <h2 style="text-align:center !important;color:white;">{{Title}}</h2>
        <form method="post">
            {% csrf_token %}
            <table id="tabl" class="table">
                {% for field in form %}
                <tr>
                    {{ field.errors }}
                    <td>{{ field.label_tag }}</td>
                    <td>{{ field }}</td>
                </tr>
            {% endfor %}
            </table>
            <input class = "btn btn-success" type="submit"  style="width: 50% !important;margin-left: 25% !important;" value="{{submit_text}}"/>
        </form>
        <br/>
        <a href="{% url link_to_next %}"><button class = "btn btn-success" style="width: 50% !important;margin-left: 25% !important;" >{{text_of_next}}</button></a>
    </div>
</div>
    <p style="margin-top:70px; color:white;font-size: medium;">Please choose another username if being <b>redirected</b> to same page<br/>As it may be alredy taken :) </p>
</div>
</body>
</html>

MyFeedapp/templates/user_saved_articles.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html lang="en">

<head>
    <title>{{Title}}</title>
    <link rel="stylesheet" href="{% static 'article.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <style>

        #articleimage{
        height: 100% !important;
        width: 100% !important;
        }

        input[type=text] {
            width: 130px;
            box-sizing: border-box;
            border: 2px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
            color:black;
            background-color: white;
            background-position: 10px 10px;
            background-repeat: no-repeat;
            padding: 12px;
            -webkit-transition: width 0.4s ease-in-out;
            transition: width 0.4s ease-in-out;
        }
         input[type=text]:focus {
            width: 40%;
            color:black;
        }
    </style>
    <script type="text/javascript">

    window.onload = function() {

        document.getElementById("loader").style.display="none";
        document.getElementById("menu").style.display="block";
        document.getElementById("articles").style.display="block";
        var save_buttons = document.getElementsByClassName("btn btn-danger");
        var i = 0;
        for(i = 0;i<save_buttons.length;i++)
        {
            save_buttons[i].onclick=function() {saveArticleFunction(this);}
            console.log(save_buttons[i].id);
        }
    };
        function saveArticleFunction(item)
        {
            var article =  item.id;
            alert("Button Pressed.");
            $.ajax({
                url: '/remove/',
                data:article,
                dataType: 'json',
                success: function (data) {
                    if (data.is_removed) {
                        document.getElementById("a"+article).style.display = "none";
                        alert(" Article removed.");
                    }
                    else{
                        alert(" Article Not removed.");
                    }
                }
            });
        }
    </script>
</head>
<body style="background-image:url({% static 'grey_wash_wall.png' %}); background-repeat:repeat; background-attachment: fixed;">
    {% include 'basePageDisplay.html' %}
    <div id="articles" style="display:none;">
        <p>.</p>
    {% if is_data_available %}
        <div class="row" style="margin-top: 70px !important;font-size: initial !important;" >
        {% for article in Articles %}
            {% if article.title %}
                <div class="col-sm-6 col-md-4" style="height: 600px !important;" id="a{{article.id}}">
                    <div class="thumbnail">
                        <img class="lib-img-show" style="width:100% !important;height:200px !important;" src="{{article.urlToImage}}" />
                        <div class="caption" style="height:300px;" >
                            <h3><a href="{{article.url}}">{{article.title}}</a></h3>
                            <p>{{article.description}}</p>
                            <div>
                             {{article.publishedAt}}
                            </div>
                            <p><button style="float: right;" id='{{article.id}}' type="button" class="btn btn-danger">Remove</button></p>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
        </div>
    {% else %}
        <h1 style="text-align:center;margin-top:200px;">You have No Saved Articles Currently</h1>
    {% endif %}

</body>
</html>
<!--author = models.CharField(max_length=50)-->
    <!--title = models.CharField(max_length=120)-->
    <!--desciption = models.CharField(max_length=700)-->
    <!--source_url = models.URLField()-->
    <!--url_to_image = models.URLField()-->
    <!--publishedAt = models.DateTimeField()-->